name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - uses: actions/checkout@v1
    - run: go generate
    - run: go build -v
    - run: go test -v
    - run: go build -v ./examples
